
/**
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class FibEvenSum {
    public static void main(String[] args) {
        int first = 1;
        int second = 2;

        int total = 0; // start with the first even term

        // for(int i = 0; i < ) {
        while(first < 4000000) {
            int temp = second;
            second = first + second;
            first = temp;

            if(first % 2 == 0) {
                total  = total + first;
            }
        }

        System.out.println(total);
    }
}
